export type Profile = { id: string; name: string; username?: string | null; image?: string | null; bio?: string | null; location?: string | null; is_private?: boolean; email?: string | null; phoneNumber?: string | null; address?: string | null };
export type PostMedia = { id: string; postId: string; userId: string; type: 'image' | 'video'; path: string; mime_type: string; width: number; height: number; duration?: number | null; size_bytes: number; thumbnail_path?: string | null; sort_order: number };
export type Post = { id: string; userId: string; body: string; visibility: 'public' | 'followers' | 'private'; status: 'draft' | 'published'; created_at: string; updated_at: string; user?: Profile; media?: PostMedia[]; like_count?: number; comment_count?: number; liked?: boolean; bookmarked?: boolean };
export type Like = { id: string; postId: string; userId: string; reaction: string; created_at: string };
export type Comment = { id: string; postId: string; userId: string; parentId?: string | null; text: string; created_at: string; updated_at?: string; user?: Profile; like_count?: number; liked?: boolean };
export type Notification = { id: string; senderId?: string | null; receiverId: string; type: string; title: string; data: Record<string, unknown>; dedupe_key: string; read_at?: string | null; created_at: string; sender?: Profile };
export type Follow = { id: string; follower_id: string; following_id: string; status: 'pending' | 'accepted'; created_at: string; updated_at: string };
export type Bookmark = { id: string; userId: string; postId: string; created_at: string };
export type Block = { id: string; blocker_id: string; blocked_id: string; created_at: string };
export type Mute = { id: string; userId: string; muted_id: string; created_at: string };
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'read' | 'failed';
export type MessageType = 'text' | 'image' | 'video' | 'audio' | 'file' | 'location';
export type MessageReaction = { emoji: string; count: number; reacted_by_me: boolean };
export type MessageReplyPreview = { id: string; userId: string; text: string; message_type: MessageType; media_path?: string | null; deleted_at?: string | null };
export type Message = {
  id: string;
  client_id?: string | null;
  conversation_id: string;
  userId: string;
  text: string;
  message_type: MessageType;
  media_path?: string | null;
  mime_type?: string | null;
  created_at: string;
  deleted_at?: string | null;
  deleted_by_sender?: boolean;
  status?: MessageStatus;
  reply_to?: MessageReplyPreview | null;
  reactions?: MessageReaction[];
};
export type Conversation = { id: string; user_low: string; user_high: string; created_at: string; updated_at: string; other_user?: Profile; latest_message?: Message | null; unread_count?: number };
export type NotificationPreferences = { userId: string; push_enabled: boolean; messages: boolean; likes: boolean; comments: boolean; replies: boolean; mentions: boolean; follows: boolean; follow_requests: boolean; message_previews: boolean; updated_at: string };
export type StoryMediaType = 'image' | 'video';
export type StoryAudience = 'followers' | 'close_friends';
export type Story = { id: string; author_id: string; media_type: StoryMediaType; media_path: string; mime_type: string; thumbnail_path?: string | null; width: number; height: number; duration?: number | null; caption?: string | null; audience: StoryAudience; created_at: string; expires_at: string; author?: Profile; viewed?: boolean; view_count?: number | null; can_reply?: boolean };
export type CloseFriend = { id: string; friend_id: string; created_at: string; user: Profile };
export type CloseFriendCandidate = Profile & { is_close_friend: boolean };
export type StoryViewState = 'none' | 'partial' | 'all';
export type StoryRingState = 'none' | 'unviewed' | 'viewed';
export type StoryTrayItem = { author: Profile; story_count: number; unviewed_count: number; latest_story_at: string; has_close_friends: boolean; is_own: boolean };
export type StoryDraft = { mediaType: StoryMediaType; uri: string; mimeType: string; width: number; height: number; duration: number | null; fileSize: number | null; thumbnailUri: string | null };
export type StoryErrorCode = 'unsupportedMedia' | 'mediaTooLarge' | 'videoTooLong' | 'videoTooShort' | 'captionTooLong' | 'invalidAudience' | 'invalidMedia' | 'noCloseFriends' | 'permissionDenied' | 'uploadFailed' | 'publishFailed' | 'rateLimited' | 'storyUnavailable';
export type StoryUploadStatus = 'idle' | 'preparing' | 'uploading' | 'publishing' | 'success' | 'failed';
export type StoryUploadState = { status: StoryUploadStatus; progress: number; error: StoryErrorCode | null };
export type StoryViewerEntry = { viewer: Profile; viewed_at: string };
